env:
  browser: true
  es2021: true
  node: true,
extends:
  - plugin:@next/next/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
plugins:
  - react
rules: {
  "react/jsx-props-no-spreading": "off",
}
