env:
  browser: true,
  es2021: true,
  node: true,
extends:
  - plugin:@next/next/recommended
  - airbnb
  - next 
  - next/core-web-vitals

overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
"react/jsx-props-no-spreading": "off",
"react/no-unescaped-entities": "off",
"@next/next/no-page-custom-font": "off",
"linebreak-style": ["error", process.env.NODE_ENV === 'prod' ? "unix" : "windows"],
 }
