env:
  browser: true
  es2021: true
  node: true,
extends:
  - plugin:@next/next/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
plugins:
  - react
rules:
  {
    'linebreak-style': ['error', 'windows'],
    'react/jsx-props-no-spreading': 'off',
    'jsx-a11y/anchor-is-valid': 'off',
    'jsx-a11y/no-static-element-interactions': 'off',
    'jsx-a11y/click-events-have-key-events': 'off',
    'jsx-a11y/no-confusing-arrow': 'off',
    'no-noninteractive-element-interactions': 'off',
  }
